version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '0.0.0.0:6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass Password
    volumes: 
      - cache:/data

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_CONF_DIR:-./nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ./sites:/var/www/html
    depends_on:
      - cache
    restart: always

volumes:
  cache:
    driver: local